# Generated by Django 3.2.13 on 2022-05-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Creada', 'Creada'), ('Iniciada', 'Iniciada'), ('Suspendida', 'Suspendida'), ('Finalizada', 'Finalizada'), ('Incompleta', 'Incompleta')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
    ]
